services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_map
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data