services:
  db:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_map
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      